#encoding UTF-8
<div class="entry-content about-outer" itemprop="text">
    <br>
    <h2>Πληροφορίες για τον μετεωρολογικό σταθμό</h2>

    <ul>
        <li>Tύπος Υπολογιστή Σέρβερ: hp110 mini </li>
        <li>Διανομή : sparky linux</li>
        <li>Tύπος Μετεωρολογικού Σταθμού: $station.hardware</li>
        <li>Σέρβερ ανοικτός: $station.os_uptime</li>
        <li>WeeWX Ανοικτό: $station.uptime</li>
        <li>WeeWX Εκδοση: $station.version</li>
        <li>Belchertown Skin Εκδοση: $belchertown_version</li>
        <li>Θερμοκρασία κονσόλας: $current.inTemp</li>
        <li>Υγρασία κονσόλας: $current.inHumidity</li>
    </ul>
   
    <p>Mετάφραση-μετατροπή σελίδας στα Ελληνικά MetFM 2021</p>
</div>
